"""add a colmun post class to posts table

Revision ID: b165819dd57b
Revises: 4f3b0786f943
Create Date: 2024-12-18 14:13:36.371423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b165819dd57b'
down_revision: Union[str, None] = '4f3b0786f943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_class', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_class')
    # ### end Alembic commands ###
